landuage: node_js
node_js:
  - "11"
notifications:
  email:
    recipients:
      - 519495771@qq.com
  on_success: change
  on_failure: always
cache:
  directories:
    - node_modules
before_script:
  - yarn
script:
  - npm run build
after_success:
  - npm run deploy


git:
  depth: 5
env:
  global:
    secure: IF33SQmSvXuTXYkCfveG3CZJbm65eN8WgPRNExu7RRc5hf3ixccYeOZDeIYwxswRzzw3sAnb/6derBSitXbWu76qVo5+n6sqx5NhzQm+p66wbn35Fz43UGf+gyqCcz90YGCQUdHxE/duU6ZnGqlXrCckYZOrFf6YSMgldO4FJjz6dR7RZOlGZ/X3YDklPFMZrwNsMUxoAI2riTwLcwhkazUJ9mi3YHUuuW3OBslrcDxdZCtFEIZGt1/sICpv0uyPowjB0RUAFv/8/hNNT4/669aEgxNzPKlXk8Q68Tmf53jy75PWKNFN/pfswulV45ltKWVgP3SM3143urY+8OWhEj1lyeMI93zB3QuW9QBqWifWEkuPed8qmEqEAxH1ys/7yyAUHzbRO9gaRcWHDb5aQ6Evjkw5FnwsqMd8erq02FkiCCKPm3LBYgtairzWiN8arDS8edyStPdXn0+9UNevdRlX0s/OL7q1dWb2kI66Fj4YiBaAjzqNeeLhCfeu1vMcAuU3av1y1cMzp7atHnNTylMaylLVbsLLKBDgY8lSiovPIV8K7DFW4dinFgEAEx3oRSIbz+cK0B2kghLmJZZZd/VJcdXqD1IKqJ/PU/ddmI1bo08YrRpTvm967k8FF6t1fVSDW7DUVsPn9YKm+K4nObjB74Kp/WNKHRiufxaPxYA=
